services:
  app:
    hostname: app
    build: .
    ports:
      - 3000:3000
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PPORT: 5432
    depends_on:
      - 'db'

  db:
    image: postgres:14.3-alpine
    hostname: db
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres