apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name}}
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer
