apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-services
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: {{ .Release.Name}}
    type: LoadBalancer