repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: postgresql
    namespace: default
    chart: bitnami/postgresql
    version: 16.0.1
    values: [./ruby-app/postgres.yaml]

  - name: ruby-app
    namespace: default
    chart: ./ruby-app/
