replicaCount: 1
namespace: "default"
containerPort: 3000

image:
  registry: hub.docker.com
  repository: mishila/mylab-ruby-app
  tag: latest

postgresql:
  host: postgresql
  username: postgres
  port: 5432
  password:
  secrets:
    name: postgresql
    key: postgres-password

igress:
  enabled: true

service:
  type: ClusterIP
  port: 80
  targetPort: 3000
