name: Docker build and push image
on:  
    pull_request:
        types: [opened, closed]
        branches: [main]
jobs:
    pull_request_open:
        if: github.event.action == 'opened'
        runs-on: ubuntu-latest

        steps:
          - name: echo
            run: echo "New pull request"

    build_and_push:
        if: github.event.action == 'closed'
        runs-on: ubuntu-latest
        env:
            USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            IMAGE: ${{ vars.IMAGE_NAME }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Docker Login
              uses: docker/login-action@v3
              with:
                username: ${{ env.USERNAME }}
                password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with: 
                push: true
                tags: |
                    ${{ env.USERNAME }}/${{ env.IMAGE }}:latest
                cache-from: type=registry,ref=${{ env.USERNAME }}/${{ env.IMAGE }}:buildcache
                cache-to: type=registry,ref=${{ env.USERNAME }}/${{ env.IMAGE }}:buildcache,mode=max
                platforms: linux/amd64,linux/arm64